In [19]:
import sys

#for path in sys.path:
#    print(path)

sys.path.append("C:/Users/rober/si/src/si/data")
sys.path.append("C:/Users/rober/si/src/si/io")

import numpy as np
import pandas as pd
from dataset import Dataset
from CSV import read_csv

## 1) Neste exercício, vamos usar o iris dataset. Carrega o *iris.csv* usando o método read apropriado para o tipo de ficheiro.

In [20]:
data = read_csv("C:/Users/rober/si/datasets/iris/iris.csv", label=4)

## 2) Seleciona a primeira variável independente e verifica a dimensão do array resultante.

In [21]:
print(data.X[:,0].shape)

(150,)


## 3) Seleciona as últimas 5 amostras do iris dataset. Qual a média das últimas 5 amostras para cada variável independente/feature?

In [33]:
elem = data.X[-5:]
elem_mean = np.mean(data.X[-5:], axis=1)

print("Data:\t\t       Mean:\n----------------------------")
for i in range(len(elem)):
    print(elem[i]," -> ",round(elem_mean[i],3))

Data:		       Mean:
----------------------------
[6.7 3.0 5.2 2.3]  ->  4.3
[6.3 2.5 5.0 1.9]  ->  3.925
[6.5 3.0 5.2 2.0]  ->  4.175
[6.2 3.4 5.4 2.3]  ->  4.325
[5.9 3.0 5.1 1.8]  ->  3.95


## 4) Seleciona todas as amostras do dataset com valor superior ou igual a 1. Nota que o array resultante deve ter apenas amostras com valores iguais ou superiores a 1 para todas as features.

In [35]:
df = pd.DataFrame(data.X)
df.insert(4, "Especie", data.y)

df_sup1 = df.loc[(df[0]>1) & (df[1]>1) & (df[2]>1) & (df[3]>1)]
print(df_sup1)

       0    1    2    3          Especie
50   7.0  3.2  4.7  1.4  Iris-versicolor
51   6.4  3.2  4.5  1.5  Iris-versicolor
52   6.9  3.1  4.9  1.5  Iris-versicolor
53   5.5  2.3  4.0  1.3  Iris-versicolor
54   6.5  2.8  4.6  1.5  Iris-versicolor
..   ...  ...  ...  ...              ...
145  6.7  3.0  5.2  2.3   Iris-virginica
146  6.3  2.5  5.0  1.9   Iris-virginica
147  6.5  3.0  5.2  2.0   Iris-virginica
148  6.2  3.4  5.4  2.3   Iris-virginica
149  5.9  3.0  5.1  1.8   Iris-virginica

[93 rows x 5 columns]


## 5) Seleciona todas as amostras com a classe/label igual a ‘Iris-setosa’. Quantas amostras obténs?

In [36]:
X_is = data.X[data.y=="Iris-setosa",:]
print(X_is)
print(len(X_is))

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]]
50


In [38]:
#OU
df_is = df[df["Especie"]=="Iris-setosa"]
print(df_is)
print()
print(len(df_is))

      0    1    2    3      Especie
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.5  0.2  Iris-setosa
11  4.8  3.4  1.6  0.2  Iris-setosa
12  4.8  3.0  1.4  0.1  Iris-setosa
13  4.3  3.0  1.1  0.1  Iris-setosa
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
16  5.4  3.9  1.3  0.4  Iris-setosa
17  5.1  3.5  1.4  0.3  Iris-setosa
18  5.7  3.8  1.7  0.3  Iris-setosa
19  5.1  3.8  1.5  0.3  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa
22  4.6  3.6  1.0  0.2  Iris-setosa
23  5.1  3.3  1.7  0.5  Iris-setosa
24  4.8  3.4  1.9  0.2  Iris-setosa
25  5.0  3.0  1.6  0.2  Iris-setosa
26  5.0  3.4  1.6  0.4  Iris